# Generated by Django 3.2.9 on 2021-12-30 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
