# Generated by Django 3.2.9 on 2022-01-12 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0002_auto_20211230_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='auth.user'),
            preserve_default=False,
        ),
    ]
