# Generated by Django 3.2.9 on 2022-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_countries_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='country_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
