# Generated by Django 3.2.9 on 2022-01-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_countries_country_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
