# Generated by Django 3.2.9 on 2022-01-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_alter_countries_country_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_image',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/images/1C3B237F-1289-491B-B8F3-833832E0AB20.jpeg', null=True, upload_to='images/'),
        ),
    ]
